version: "3"
services:
  windows:
    image: dockurr/windows
    container_name: windows
    devices:
      - /dev/kvm
    cap_add:
      - NET_ADMIN
    ports:
      - 8006:8006           # GUI web (noVNC)
      - 3390:3389/tcp       # RDP
      - 3390:3389/udp
    stop_grace_period: 1m
    restart: unless-stopped
    environment:
      VERSION: ""           # Kosongkan agar tidak auto-download
      MANUAL: "Y"           # Manual install dari ISO
      DISK_SIZE: "5G"      # Ukuran disk awal
      RAM_SIZE: "4G"
      CPU_CORES: "8"
    volumes:
      - ./data:/storage              # Di mana data.img akan dibuat
      - ./iso/tiny10.iso:/boot.iso   # ISO kamu (preloaded)
