version: "3" 
services:
  windows:
    image: isaccanedo/windows-inside-a-docker-container
    container_name: windows
    devices:
      - /dev/kvm
    cap_add:
      - NET_ADMIN
    ports:
      - 8006:8006           # Akses GUI via browser
      - 3390:3389/tcp       # Remote Desktop Protocol
      - 3390:3389/udp
    stop_grace_period: 2m
    restart: always
    environment:
      VERSION: "11l"        # Windows 11 LTSC: lebih ringan
      RAM_SIZE: "4G"        # Efisien, cukup untuk multitasking ringan
      CPU_CORES: "8"        # Bisa diperkecil, tapi aman untuk performa optimal
      DISK_SIZE: "7G"       # Ideal untuk sistem dasar dengan buffer aman
    volumes:
      - ./data:/storage     # Persistent volume untuk data user
