version: "3"
services:
  windows:
    image: dockurr/windows
    container_name: windows
    devices:
      - /dev/kvm
    cap_add:
      - NET_ADMIN
    ports:
      - 8006:8006
      - 3390:3389/tcp
      - 3390:3389/udp
    stop_grace_period: 1m
    restart: unless-stopped
    environment:
      VERSION: "7e"
      RAM_SIZE: "2G"
      CPU_CORES: "2"
      DISK_SIZE: "5G"
    volumes:
      - ./data:/storage
