version: "3"
services:
  windows:
    image: dockurr/windows
    container_name: windows
    devices:
      - /dev/kvm
    cap_add:
      - NET_ADMIN
    ports:
      - 8006:8006
      - 3390:3389/tcp
      - 3390:3389/udp
    stop_grace_period: 1m
    restart: unless-stopped
    environment:
      VERSION: ""
      DISK_SIZE: ""
      RAM_SIZE: "4G"
      CPU_CORES: "8"
    volumes:
      - ./data:/storage
