version: "3"
services:
  windows:
    image: dockurr/windows
    container_name: windows
    devices:
      - /dev/kvm
    cap_add:
      - NET_ADMIN
    ports:
      - 8006:8006           # Web GUI (VNC-like)
      - 3390:3389/tcp       # RDP
      - 3390:3389/udp
    stop_grace_period: 1m
    restart: unless-stopped
    environment:
      VERSION: ""           # Tidak download ISO baru
      DISK_SIZE: ""         # Tidak buat disk baru
      RAM_SIZE: "4G"
      CPU_CORES: "8"
    volumes:
      - ./windows/data:/storage
